### ISSUE TITLE
"Field resolver returned a single value, expected a collection of values." when using resolve/with-context

### ISSUE THREAD

**Issue by glittershark** [oliyh/superlifter#19]
Something like this:
```clojure
(require '[com.walmartlabs.lacinia.resolve :as resolve])

(defn resolve-foo-bars
  [ctx _ {foo-id ::foo/id}]
  (with-superlifter ctx
    (resolve/with-context
      (sl/enqueue! :foo-bars (->FetchBars foo-id))
      {::foo/id foo-id})))
```

Used to work before around 7767c1690193b77293ed63135f3d3708f4963a69, but now gives `"Field resolver returned a single value, expected a collection of values."`

**Comment by oliyh** [comment]
Thanks for reporting this and the simple step to reproduce. Does it work if you remove the `with-context`? 

`enqueue!` returns a promesa promise, not a lacinia one. The `with-superlifter` macro returns a lacinia promise, which is presumably what `with-context` expects, so I think you just need to make `with-context` the outer form, and have `with-superlifter` inside it.

If that turns out to be correct I'd be surprised how it ever worked before!

**Comment by glittershark** [comment]
I had the same thought initially, but this also fails with the same error:
```clojure
(defn resolve-foo-bars
  [ctx _ {foo-id ::foo/id}]
  (resolve/with-context
    (with-superlifter ctx
      (sl/enqueue! :foo-bars (->FetchBars foo-id)))
    {::foo/id foo-id}))
```

**Comment by oliyh** [comment]
Interesting, I really would expect them to fail differently at least. If you remove the `with-context` does it work? That would narrow it down at least.

Cheers

**Comment by glittershark** [comment]
Yeah, works fine without

**Comment by oliyh** [comment]
I can reproduce, but it seems to be an issue with lacinia rather than superlifter. The following code gives the same error:

```
(defn resolve-foo-bars
  [ctx _ {foo-id ::foo/id}]
  (let [p (resolve/resolve-promise)]
    (resolve/deliver! p [{:id 123} {:id 234}])
    (resolve/with-context p {::foo/id foo-id}))
```

So if lacinia doesn't support calling `with-context` on a promise then the only way to do it is calling it on the actual result that is returned in the promise. You can do it like this:

```
(require '[promesa.core :as prom])

(defn resolve-foo-bars
  [ctx _ {foo-id ::foo/id}]
  (with-superlifter ctx
    (prom/then (sl/enqueue! :foo-bars (->FetchBars foo-id))
                        (fn [result]
                          (resolve/with-context result {::foo/id foo-id})))))
```
