### ISSUE TITLE
`start-buckets!` creates more threads than necessary

### ISSUE THREAD

**Issue by namenu** [oliyh/superlifter#29]
`start-buckets!` is using `swap!` to update bucket information, and `swap!` must have no side effects. [^1]
https://github.com/oliyh/superlifter/blob/eb89a4046154c9bc032ef964ac5cef6a03f80365/src/superlifter/core.cljc#L194-L200

And this situation can easily be happening where the server is under heavy load.

This results in creating many unnecessary threads, hogging the thread pool.

[^1]: https://clojuredocs.org/clojure.core/swap! - Note that f may be called multiple times, and thus should be free of side effects.

**Comment by namenu** [comment]
@oliyh Great!

FYI, we've been workaround with this fix.
https://github.com/green-labs/superlifter/commit/4fe1e26d8090713c2826468c44bf8302d5284289

**Comment by oliyh** [comment]
Hi,

Thanks for sharing your workaround. Just reading through it, here's what I see:
- Calling `start-trigger` now assocs a `:start-fn` to each bucket, rather than actually starting it
- `(:buckets context)` is no longer an atom, but `(-> context :buckets bucket-id)` is

This means that adding a bucket dynamically is not really possible anymore - in fact the code still has `swap-vals` on `(:buckets context)` which won't work anymore, so I guess you are not using this feature: https://github.com/green-labs/superlifter/commit/4fe1e26d8090713c2826468c44bf8302d5284289#diff-53fa11e40c1e91d8226bb3a21d4ee41f1c4f14f02ea75e6c4e9e43b57301944aR228

So I don't think I can use your solution as it is, but it has given me some ideas thank you.

**Comment by oliyh** [comment]
Hi, I've pushed `0.1.5-SNAPSHOT` to clojars with a fix - are you able to verify it works for your use case?

Cheers
